esphome:
  name: dht_11
  build_path: ./builds/dht-11
  platform: ESP8266
  board: thingdev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable over the air updates
ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: !secret mqtt_port

  # Set to true when finished testing to set MQTT retain flag
  discovery_retain: false
sensor:
  - platform: dht
    pin: 13
    model: DHT11
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
